### ISSUE TITLE
How is this loader different than pug-loader?

### ISSUE THREAD

**Issue by dland512** [willyelm/pug-html-loader#22]
What's the difference between this loader and [this one](https://github.com/pugjs/pug-loader)?

**Comment by willyelm** [comment]
In order to have **pug-loader** working you need to compile it manually on each import, this **package** helps you if you are looking to have the compiled text at once its useful if you have a angular application and you want to reference your template without variables directly. to have the same effect using **pug-loader** you'll need to use **pug-loader** in combination with **apply-loader** and **raw-loader** or **to-string-loader**.
